"""empty message

Revision ID: ac8aa1ef4c06
Revises: 
Create Date: 2025-07-03 00:48:43.570921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8aa1ef4c06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'sizes', ['size_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('size_id')

    # ### end Alembic commands ###
