"""empty message

Revision ID: dabfc2ee2d44
Revises: 
Create Date: 2025-07-07 23:08:42.151867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabfc2ee2d44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('damage_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('deposit_returned', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('deposit_returned')
        batch_op.drop_column('damage_level')
        batch_op.drop_column('deposit')

    # ### end Alembic commands ###
