"""empty message

Revision ID: eb59d8b6fa45
Revises: 
Create Date: 2025-07-07 16:38:38.607306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb59d8b6fa45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_return_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('is_late', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('late_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('late_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('late_fee')
        batch_op.drop_column('late_days')
        batch_op.drop_column('is_late')
        batch_op.drop_column('actual_return_date')

    # ### end Alembic commands ###
